# Generated by Django 4.2 on 2023-04-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0002_message_from_user_message_to_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
