# Generated by Django 4.2 on 2023-04-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0003_delete_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpage',
            name='insta_name',
            field=models.CharField(default='potty', max_length=200),
            preserve_default=False,
        ),
    ]
