# Generated by Django 4.2 on 2023-04-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0004_socialpage_insta_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpage',
            old_name='insta_name',
            new_name='insta_username',
        ),
    ]
